(function(){function g(a,b,c){a.addEventListener?a.addEventListener(b,c,!0):a.attachEvent&&a.attachEvent("on"+b,c)}function e(a){this.tracker=a}function h(a){try{return a.split("/")[2]}catch(b){return""}}function k(a){for(var b="",c=0;c<a;c++)b+="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".charAt(Math.floor(62*Math.random()));return b}function l(){var a=new Date;return[a.getFullYear(),("0"+(a.getMonth()+1)).slice(-2),("0"+a.getDate()).slice(-2)].join("/")+" "+[("0"+a.getHours()).slice(-2),
("0"+a.getMinutes()).slice(-2),("0"+a.getSeconds()).slice(-2),("00"+a.getMilliseconds()).slice(-3)].join(":")}e.prototype.dimensions=function(a){var b=this.tracker.get("clientId");"undefined"!==typeof a.clientid&&this.tracker.set("dimension"+a.clientid,b);"undefined"!==typeof a.sessionid&&this.tracker.set("dimension"+a.sessionid,b+"#"+k(8));"undefined"!==typeof a.timestamp&&this.tracker.set("dimension"+a.timestamp,l());"undefined"!==typeof a.ipaddress&&this.tracker.set("dimension"+a.ipaddress,"{{ipaddress}}");
"undefined"!==typeof a.useragent&&this.tracker.set("dimension"+a.useragent,navigator.userAgent)};e.prototype.spamFilter=function(a){for(var b=document.referrer,c=a.dimension.value,d="100dollars-seo.com semaltmedia.com videos-for-your-business.com buttons-for-website.com success-seo.com video--production.com".split(" "),f=0;f<d.length;f++)0<=b.indexOf(d[f])&&(c="Spam Traffic");this.tracker.set("dimension"+a.dimension.index,c)};e.prototype.source=function(){if(!(0<=location.search.indexOf("utm_source"))){var a=
h(document.referrer),b=void 0;a.match(/t\.co/)&&(b="twitter.com");a.match(/(m\.|l\.|lm\.)?facebook\.com/)&&(b="facebook.com");b&&this.tracker.set("campaignSource",b)}};e.prototype.medium=function(){if(!(0<=location.search.indexOf("utm_medium"))){var a=h(document.referrer),b=void 0;0<=a.indexOf("mail.yahoo.co.jp")&&(b="email");0<=a.indexOf("mail.live.com")&&(b="email");0<=a.indexOf("mail.google.com")&&(b="email");0<=a.indexOf("alpha-mail.ne.jp")&&(b="email");"email.excite.co.jp"==a&&(b="email");"outlook.office365.com"==
a&&(b="email");"mail.ocn.ne.jp"==a&&(b="email");"webmail.sso.biglobe.ne.jp"==a&&(b="email");"webmail.so-net.ne.jp"==a&&(b="email");"eowebmail.eonet.jp"==a&&(b="email");"mail.auone-net.jp"==a&&(b="email");"mail.goo.jp"==a&&(b="email");"mail.commufa.jp"==a&&(b="email");"webmail.cyberhome.ne.jp"==a&&(b="email");a.match(/mail[0-9]+.bizmail[0-9]+.com/)&&(b="email");a.match(/t.co/)&&(b="social");0<=a.indexOf("t.co")&&4==a.length&&(b="social");a.match(/(m.|l.|lm.)?facebook\.com/)&&(b="social");"reader.livedoor.com"==
a&&(b="rss");"feedly.com"==a&&(b="rss");"feeds.feedburner.com"==a&&(b="rss");b&&this.tracker.set("campaignMedium",b)}};e.prototype.tel=function(){function a(a){b.send("event","TEL Link","Click",a.target.href)}for(var b=this.tracker,c=document.querySelectorAll("a"),d=0;d<c.length;d++)0<=c[d].href.indexOf("tel:")&&g(c[d],"click",a)};e.prototype.outbound=function(){function a(a){b.send("event","Outbound Link","Click",a.target.href)}for(var b=this.tracker,c=document.querySelectorAll("a"),d=0;d<c.length;d++)-1==
c[d].href.indexOf(location.hostname)&&0<=c[d].href.indexOf("http")&&g(c[d],"click",a)};e.prototype.youtube=function(){function a(a){var c=a.target.getVideoData();a=a.data;b.send("event","Youtube Action",a==YT.PlayerState.ENDED?"YT.PlayerState.ENDED":a==YT.PlayerState.PLAYING?"YT.PlayerState.PLAYING":a==YT.PlayerState.PAUSED?"YT.PlayerState.PAUSED":a==YT.PlayerState.BUFFERING?"YT.PlayerState.BUFFERING":a==YT.PlayerState.CUED?"YT.PlayerState.CUED":a==YT.PlayerState.UNSTARTED?"YT.PlayerState.UNSTARTED":
"Unknown",c.video_id+" : "+c.title)}var b=this.tracker;window.onYouTubeIframeAPIReady=function(){for(var b=document.querySelectorAll("iframe"),c=0;c<b.length;c++)0<=b[c].src.indexOf("youtube.com/embed/")&&0<=b[c].src.indexOf("enablejsapi=1")&&(new YT.Player(b[c])).addEventListener("onStateChange",a)};var c=document.createElement("script");c.src="https://www.youtube.com/iframe_api";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(c,d)};(function(a,b){var c=window[window.GoogleAnalyticsObject||
"ga"];c&&c("provide",a,b)})("powerup",e);(function(){var a=document.createElement("img"),b=[];b.push("referrer="+(document.referrer||"direct"));b.push("display_size="+[window.screen.width,window.screen.height].join("x"));b.push("window_size="+[window.innerWidth,window.innerHeight].join("x"));b.push("title="+document.title);b.push("no_cache="+(new Date).getTime());a.src="//power-dmp.link/pixel.gif?"+b.join("&");a.style="display: none;";document.body.appendChild(a)})()})();
